// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyD9QCKErNKaI2bHoMODgvL8Y8xXiHrP4',
    appId: '1:604350127129:web:495345928286bfd5f79e88',
    messagingSenderId: '604350127129',
    projectId: 'gasfuel-3c164',
    authDomain: 'gasfuel-3c164.firebaseapp.com',
    storageBucket: 'gasfuel-3c164.appspot.com',
    measurementId: 'G-P15X87BJ2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiwjgqbNDNoogMqgIbDkcIOxlbSL8s9tA',
    appId: '1:604350127129:android:32f3cdbee3ee9be4f79e88',
    messagingSenderId: '604350127129',
    projectId: 'gasfuel-3c164',
    storageBucket: 'gasfuel-3c164.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZm_zZbRBe_05nNcrquiHpCQkwnPbApLA',
    appId: '1:604350127129:ios:f381719528f94f3cf79e88',
    messagingSenderId: '604350127129',
    projectId: 'gasfuel-3c164',
    storageBucket: 'gasfuel-3c164.appspot.com',
    iosClientId: '604350127129-phmc6gugjoakm2803am418akmh50av5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.gasFuel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZm_zZbRBe_05nNcrquiHpCQkwnPbApLA',
    appId: '1:604350127129:ios:f381719528f94f3cf79e88',
    messagingSenderId: '604350127129',
    projectId: 'gasfuel-3c164',
    storageBucket: 'gasfuel-3c164.appspot.com',
    iosClientId: '604350127129-phmc6gugjoakm2803am418akmh50av5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.gasFuel',
  );
}
